export const stations = [
  { value: "reg", label: "Registro", order: 1 },
  { value: "nur", label: "Enfermera" , order: 2 },
  { value: "doc", label: "Doctor", order: 3 },
  { value: "pt", label: "Fisioterapia", order: 4 },
  { value: "ped", label: "Pediatria", order: 5 },
  { value: "nut", label: "Nutricion", order: 6 },
  { value: "psi", label: "Psicología", order: 7 },
  { value: "obs", label: "Observation", order: 8 },
  { value: "pha", label: "Farmacia", order: 9 },    
  { value: "lab", label: "Laboratorio", order: 10 },
  { value: "og", label: "Obstetria/Ginecología", order: 11},
  { value: "den", label: "Ondontología", order: 12 },
  { value: "pra", label: "Oración", order: 13 },
];
